# Monorepo Render config for Python volume service and Node backend
services:
  - type: web
    name: backend2-stl-volume
    env: python
    rootDir: 3D-Wizard-Website-Python-Backend-main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true

  - type: web
    name: threed-wizard-website-backend
    env: node
    rootDir: 3D-Wizard-Website-Backend-main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: STL_VOLUME_API_URL
        value: "CHANGE_ME_AFTER_PYTHON_DEPLOYS"  # e.g., https://backend2-stl-volume.onrender.com/calculate-volume
      - key: CORS_ALLOWED_ORIGINS
        value: "https://3-d-wizard-website.vercel.app"
      # Optional Cloudinary/Sheets (set only if you use them)
      - key: CLOUDINARY_CLOUD_NAME
        value: ""
      - key: CLOUDINARY_API_KEY
        value: ""
      - key: CLOUDINARY_API_SECRET
        value: ""
      - key: GOOGLE_SERVICE_ACCOUNT_PATH
        value: "src/credentials/service-account-key.json"
      - key: GOOGLE_SHEETS_ID
        value: ""

